# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: '       '

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: '        '

menu:
- {name: '随笔',          url: 'jottings'}
- {name: '文档笔记',      url: 'notes'}
- {name: '项目',          url: 'projects'}
- {name: '分享',          url: 'sharing'}
- {name: '关于',          url: 'about'}
#- {name: '联系',          url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://x.com/ZHOUHENGAI'}
- {icon: 'facebook', link:   'https://www.facebook.com/'}
- {icon: 'instagram', link:  'https://www.instagram.com/zhouheng644'}
- {icon: 'envelope', link:   'mailto:zhouheng644@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: '下一页'
  previous_page: '上一页'

sharing_button_prompt: 'Feel free to share!'

related_posts: '还有一点东西...'

post_date_prefix: 'Written on'
